CTECH-1140 poll nuget for sdk

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -9,6 +9,7 @@ on:
     branches: [ master ]
   pull_request:
     branches: [ master ]
+  workflow_dispatch:
 
 jobs:
   # This workflow contains a single job called "build"
@@ -31,10 +32,36 @@ jobs:
           else
             exit 1
           fi
-      
-      - name: Run tests on MASTER branch
-        if: ${{ github.base_ref == 'master' || github.ref == 'refs/heads/master' }}
-        env: 
+     
+      - name: setup .NET
+        uses: actions/setup-dotnet@v2
+        
+      - name: restore dependencies
+        run: |          
+
+          retries=2
+          found=0
+
+          while [[ $retries -ge 0 && $found == 0 ]]; do
+
+              if ! dotnet restore sdk/Finbourne.Configuration.Sdk.Extensions.sln ; then
+                  echo "[ERROR] unable to restore dependencies, attempts remaining: $retries"
+                  sleep 30
+                  ((retries--))
+              else
+                  echo "[INFO] successfully installed dependencies"
+                  found=1
+              fi
+
+          done
+
+          if [ $found == 0 ] ; then
+            echo "[ERROR] unable to restore dependencies"
+            exit 1
+          fi
+
+      - name: run tests
+        env:
           FBN_TOKEN_URL: ${{ secrets.MASTER_FBN_TOKEN_URL }}
           FBN_USERNAME: ${{ secrets.MASTER_FBN_USERNAME }}
           FBN_PASSWORD: ${{ secrets.MASTER_FBN_PASSWORD }}
@@ -43,13 +70,7 @@ jobs:
           FBN_CONFIGURATION_API_URL: ${{ secrets.MASTER_FBN_CONFIGURATION_API_URL }}
           FBN_APP_NAME: ${{ secrets.MASTER_FBN_CLIENT_ID }}
           FBN_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.MASTER_FBN_ACCESS_TOKEN }}
-        run: | 
-          echo "env variables for MASTER have been set"
-          echo "Changing directory into sdk directory"
-          cd sdk          
-          echo "Running the tests..."
-          docker-compose up --abort-on-container-exit
-          echo "Tests COMPLETED"
+        run: dotnet test --configuration Release --verbosity normal sdk/Finbourne.Configuration.Sdk.Extensions.sln
 
       - name: Slack notification
         uses: 8398a7/action-slack@v3
